name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm --prefix backend install

      - name: Lint backend
        run: npm --prefix backend run lint

      - name: Install frontend dependencies
        run: npm --prefix frontend install

      - name: Lint frontend
        run: npm --prefix frontend run lint

      - name: Build frontend
        run: npm --prefix frontend run build
